[project]
name = "airtable-ops-automation"
version = "0.1.0"
description = "Lightning in a Bottle 2026"
readme = "README.md"
authors = [
    { name = "Ryan Brown", email = "ryan@mimetics.io" }
]
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.1",
    "requests>=2.32.0",
]

[project.scripts]
airtable-ops-automation = "airtable_ops_automation.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
